### ISSUE TITLE
Teraz gramy button

### ISSUE THREAD

**Issue by nalexandraq** [RadioAktywne/ra-app#49]
- button teraz gramy na main page'u
- rds powoli przesuwa się, tak jak w playerze na dole
- ruchome tło, kiedy odpalony stream (trzeba sprawdzić czy lepiej zadziała gif czy animacja tła i czy nie będzie muliła aplikacja)
- animacja play/pause jak w playerze na dole
- onclick play/pause

![Image](https://github.com/RadioAktywne/ra-app/assets/73692280/355a5586-8d30-4aad-858d-954215818853)

**Comment by nalexandraq** [comment]
bloker dla tego taska: ongoing review polecany artykuł button

**Comment by tymwitko** [comment]
Część związana z tłem przeniesiona do https://github.com/RadioAktywne/ra-app/issues/75
